### ISSUE TITLE
'NSWorkspace' is unavailable in Mac Catalyst

### ISSUE THREAD

**Issue by andreweades** [JohnSundell/Files#103]
The new File.open() is only defined if AppKit can be imported. However, in a Mac Catalyst app, AppKit is available but NSWorkspace is not. This result in a compilation when adding Files.swift to a Mac Catalyst project.

**Comment by JohnSundell** [comment]
@andreweades Do you mind submitting a fix for this? I'm not on Catalina myself yet, so won't be able to work on this right now (since I won't be able to test that any patch I'd make actually worked), but would love to see it fixed.

It should just be a matter of adding `targetEnvironment(macCatalyst)` to the existing `#if canImport(AppKit)` compiler condition on line `460`.

**Comment by matadan** [comment]
Sure. I’ll have a go.

**Comment by JohnSundell** [comment]
Fix merged 👍
