### ISSUE TITLE
LocalizedError for errors

### ISSUE THREAD

**Issue by artemnovichkov** [JohnSundell/Files#23]
Often I use simple error handling in `catch` block:
```swift
print("\(error.localizedDescription)")
```
For pretty-printed error messages I add confirmation of `LocalizedError` protocol and implement `localizedDescription` property. What's your opinion about this approach? Why you don't use it?

**Comment by JohnSundell** [comment]
Hey @artemnovichkov 👋 The main reason I haven't implemented it yet for Files i because the errors are actually not localized 🙂 All errors should implement `description` however, so that you can print them in a nice way. But I see that `FileSystem.Item.OperationError` is actually missing an implementation for that, so weill need to fix that 😅

**Comment by JohnSundell** [comment]
Fixed in https://github.com/JohnSundell/Files/pull/30 by @VFUC 🎉
