### ISSUE TITLE
Add convenience methods for reading Codable objects

### ISSUE THREAD

**Issue by dylanslewis** [JohnSundell/Files#25]
*Note: This will require `Codable` from Swift 3.2/4, which is why I'm not submitting a PR for this yet.*

This is a proposal for adding convenience methods to use the `Codable` protocol, to allow reading a `File` directly to a decoded object type.

Example JSON `Decodable` convenience:
```swift
extension File {
	func readAsDecodedJSON<D: Decodable>(using decoder: JSONDecoder = .init()) throws -> D {
		let fileData = try read()
		return try decoder.decode(D.self, from: fileData)
	}
}
```

Example JSON `Decodable` call site:
```swift
let myObjectFile = File(path: ...)
let myObject: DecodedJSONObject = try myObjectFile.readAsDecodedJSON()
```

**Comment by JohnSundell** [comment]
Hi @dylanslewis! 👋

I consider this out of scope for Files. Since it only requires a few lines in application code, I don't see a big benefit to implement (& maintain) such an implementation in the framework itself. I also don't want to tie Files too much to one way of parsing JSON, since people use many different libraries and techniques to do so.

Keep the suggestions coming though 👍
