### ISSUE TITLE
Open PRs

### ISSUE THREAD

**Issue by clayellis** [JohnSundell/Files#88]
Hey @JohnSundell 👋 

The Files 4.0 release looks great, lots a solid improvements. Those improvements, however, have broken some of the open PRs that myself and others have written. I'm wondering whether it's worth the effort to update my PRs to work with 4.0 or whether those updates will be for naught. I'd love to see them merged, but don't want to waste any time.

If those PRs won't ever be merged, will you let me and others know so we can close them out?

Best,

Clay

**Comment by clayellis** [comment]
I realize now that that sounded pretty passive aggressive — not my intent at all and I apologize if it was received that way. Just want to know how best to contribute!

**Comment by JohnSundell** [comment]
Hi @clayellis!

No worries, I didn't find your initial post passive aggressive at all, and you're bringing up a very relevant point. It's a challenge that I've faced in general with my open source projects during the last few years, how to best incorporate community contributions. On one hand, I'm just one person, so it's really hard for me to find the time to properly review (and more importantly, maintain) the contributions that people make - especially if it's for a new feature that I'm not personally interested in myself. But on the other hand, I do value the contributions that you and others have made, and I also want to find ways to enable people to customize the tools that I build without making me a bottleneck.

With my new open source projects, such as Splash, I've more adopted a mindset of "Let me share what I've got, so that other people can use it, but if anyone wants to add features, they can create their own tool that extends it". For me, this works a lot better than having to have all new features go into the main repo, since I'm not very keen to take on the maintenance responsibility of a feature that I'll most likely never use.

That being said, I need to communicate this philosophy more clearly, and I'll also try to get better at more promptly go through incoming PRs and give feedback as to whether or not I think this ever will get merged - to set the right expectations. I'll do that with Files later this week, and will let you know what the state of your PRs are.

**Comment by clayellis** [comment]
> I've more adopted a mindset of "Let me share what I've got, so that other people can use it, but if anyone wants to add features, they can create their own tool that extends it"

I absolutely get this mindset and can understand the motivation — you've grown quite the following (which I love seeing, being an early fan of yours, by the way! It's well deserved!) and have a lot of projects going at once. Thanks for the insight, I appreciate the honesty. I think others would really appreciate hearing that as well. 

Thanks for everything you're doing for the community.

**Comment by JohnSundell** [comment]
@clayellis Thanks a lot for those kind words 🙂 I've now (finally) started going through the PRs, but will have to take them one by one as I have time, so might take a while to get through them all. But I'll do my best to get it done promptly.
